-- dashboard.lua  ── custom git dashboard configuration for Snacks.nvim
-- Contains all dashboard sections, keys, and layout logic
--
-- TODO: Future dashboard improvements
-- 1. Replace grep with workspace diagnostics searching once proper LSP support
--    is figured out for most regularly used LSPs
-- 2. Dashboard philosophy: Provide keybinds for common operations when opening
--    neovim for a project that ARE NOT common keymaps during normal coding.
--    Normal keymaps still work and muscle memory knows them - the dashboard is
--    for operations that are contextual to "just opened the project"

local utils = require("custom.snacks.utils")
local notifications = require("custom.git.notifications")
local git_utils = require("custom.git.utils")
local visual_utils = require("custom.visual.utils")
local todos = require("custom.todos")

local M = {}

-- ══════════════════════════════════════════════════════════════════════════════
-- CONFIGURATION
-- Configure your dashboard appearance here. Changes require restarting Neovim.
-- ══════════════════════════════════════════════════════════════════════════════

-- ══════════════════════════════════════════════════════════════════════════════
-- POKEMON ENV FILE EXPORT
-- Exports pokemon selection and colors to ~/.cache/pokemon-colors.env
-- This allows tmux and other tools to use the same pokemon theme colors
-- ══════════════════════════════════════════════════════════════════════════════

---Export pokemon colors to env file for use by tmux and shell
---@param name string Pokemon name
---@param shiny boolean Whether shiny variant
---@param form string|nil Form variant (e.g., "mega", "alola")
---@param colors table Color data from pokemon-colors.lua
---@param background_mode string "dark" or "light"
local function export_pokemon_to_env(name, shiny, form, colors, background_mode)
  -- Get colors for the current background mode
  local mode_colors = colors[background_mode]
  if not mode_colors then
    vim.notify(
      string.format("No colors found for background mode '%s', skipping env export", background_mode),
      vim.log.levels.WARN
    )
    return
  end

  -- Resolve fallback colors to actual hex values
  -- If a color is "fallback", we use TokyoNight defaults
  local function resolve_color(color, default)
    if color == "fallback" then
      return default
    end
    return color
  end

  -- TokyoNight Night palette defaults (matching tmux.conf)
  local dim_default = "#565f89" -- gray
  local prominent_default = "#7aa2f7" -- blue
  local bright_default = "#ff9e64" -- orange

  local dim = resolve_color(mode_colors.dim, dim_default)
  local prominent = resolve_color(mode_colors.prominent, prominent_default)
  local bright = resolve_color(mode_colors.bright, bright_default)

  -- Build env file content
  local env_content = string.format(
    [[# Auto-generated by Neovim dashboard
# Pokemon colors for tmux and shell integration
# Do not edit directly - regenerated on each nvim startup

export POKEMON_NAME="%s"
export POKEMON_SHINY="%s"
export POKEMON_FORM="%s"
export POKEMON_COLOR_DIM="%s"
export POKEMON_COLOR_PROMINENT="%s"
export POKEMON_COLOR_BRIGHT="%s"
]],
    name,
    tostring(shiny),
    form or "none",
    dim,
    prominent,
    bright
  )

  -- Write to cache file
  local env_file = vim.fn.expand("~/.cache/pokemon-colors.env")
  local f = io.open(env_file, "w")
  if f then
    f:write(env_content)
    f:close()
  else
    vim.notify(string.format("Failed to write pokemon colors to %s", env_file), vim.log.levels.ERROR)
  end
end

local CONFIG = {
  -- Dynamic gap configuration
  -- When enabled, the gap between panes will match the edge margins for balanced appearance
  -- When disabled, uses Snacks default gap of 4
  dynamic_pane_gap = true,

  -- Pokemon display configuration
  pokemon = {
    -- Set to nil to select a random pokemon from the database
    -- Otherwise, specify a pokemon name like "pikachu", "snorlax", "ho-oh", etc.
    name = "gengar",

    -- Set to true for shiny variant
    is_shiny = false,

    -- Optional form (e.g., "alola", "galar", "mega-x"), set to nil if not applicable
    form = nil,

    -- Force small sprite size (don't add -b flag even if sprite is small)
    -- This is useful if you prefer the smaller sprite aesthetic
    force_small = true,

    -- Position within the pokemon section: "top-left", "middle-middle", "bottom-right", etc.
    -- Valid positions: top-left, top-middle, top-right,
    --                  middle-left, middle-middle, middle-right,
    --                  bottom-left, bottom-middle, bottom-right
    -- Default: "middle-middle"
    position = "middle-middle",
  },

  -- Color generation configuration (for testing algorithm changes)
  generation = {
    -- Force regeneration of pokemon colors even if they exist in database
    -- Set to true when testing algorithm changes or new threshold values
    -- WARNING: This will regenerate colors on every dashboard open!
    force_regenerate = false,

    -- Colorfulness threshold for prominent color selection (default: 500, previous: 2000)
    -- Lower values favor frequency over saturation (more muted but common colors)
    -- Higher values favor vivid colors over frequency (more saturated but rare colors)
    -- Examples: 500 (balanced), 800 (moderately vivid), 1500 (very vivid), 2000 (original - very strict)
    colorfulness_threshold = 700,
  },

  -- Color theme configuration
  colors = {
    -- Background mode: "auto" (uses vim.o.background), "dark", or "light"
    -- Controls which color palette to use from pokemon color data
    background_mode = "dark",

    -- Color source overrides (applied to SnacksDashboard highlight groups)
    -- Each can be: 'auto' (from sprite), a highlight group name (e.g., 'Comment', 'Normal'), or a hex color (e.g., '#FF5733')
    -- Note: Highlight group names are case-sensitive!

    -- Title color (maps to prominent color from sprite, used for SnacksDashboardTitle)
    title_source = "auto",

    -- Key color (maps to bright color from sprite, used for SnacksDashboardKey)
    key_source = "auto",

    -- Description color (maps to dim color from sprite, used for SnacksDashboardDesc)
    desc_source = "auto",

    -- Color adjustments using tokyonight.util functions
    -- Applied after resolving the base color from source

    -- Brighten adjustments: {lightness_amount, saturation_amount}
    -- lightness_amount: increases lightness (default if omitted: 0.05)
    -- saturation_amount: increases saturation/vividness (default if omitted: 0.2)
    title_brighten = nil, -- e.g., {0.1, 0.3} to make prominent more vibrant
    key_brighten = nil, -- e.g., {0.05, 0.15} to boost key saturation
    desc_brighten = nil, -- e.g., {0, 0.1} to increase saturation only

    -- Dim adjustments: number (0-1)
    -- Blends color with background (0 = no change, 1 = full background color)
    title_dim = nil, -- e.g., 0.2 to dim prominent slightly
    key_dim = nil, -- e.g., 0.15 to reduce key contrast
    desc_dim = nil, -- e.g., 0.3 to make descriptions more subtle
  },
}

-- Calculate pokemon selection and colors (only done once at startup)
-- This ensures the pokemon doesn't change on dashboard redraws
-- Colors are always initialized regardless of pane count, but sprite only shows in dual-pane mode
local pokemon_name, pokemon_shiny, pokemon_form, pokemon_colors, color_sources, force_regenerate_active

-- Always select and load pokemon colors, even in single-pane mode
-- This ensures consistent theming across dashboard, tmux, and shell
if CONFIG.pokemon.name == nil then
  -- Random selection from database
  pokemon_name, pokemon_shiny, pokemon_form = visual_utils.select_random_pokemon()
else
  -- Use configured pokemon
  pokemon_name = CONFIG.pokemon.name
  pokemon_shiny = CONFIG.pokemon.is_shiny
  pokemon_form = CONFIG.pokemon.form
end

-- Build color sources config to pass through to generation
-- This ensures regenerated colors use the same configuration
color_sources = {
  title_source = CONFIG.colors.title_source,
  key_source = CONFIG.colors.key_source,
  desc_source = CONFIG.colors.desc_source,
  title_brighten = CONFIG.colors.title_brighten,
  key_brighten = CONFIG.colors.key_brighten,
  desc_brighten = CONFIG.colors.desc_brighten,
  title_dim = CONFIG.colors.title_dim,
  key_dim = CONFIG.colors.key_dim,
  desc_dim = CONFIG.colors.desc_dim,
}

-- Load color data for the selected pokemon
-- This will auto-generate if not in database (async)
pokemon_colors = visual_utils.ensure_pokemon_colors(
  pokemon_name,
  pokemon_shiny,
  pokemon_form,
  function()
    -- Callback: when generation completes, re-export colors and update the dashboard
    local updated_colors = visual_utils.get_pokemon_colors(pokemon_name, pokemon_shiny, pokemon_form, false)
    if updated_colors then
      export_pokemon_to_env(pokemon_name, pokemon_shiny, pokemon_form, updated_colors, CONFIG.colors.background_mode)
    end
    if Snacks and Snacks.dashboard and Snacks.dashboard.update then
      Snacks.dashboard.update()
    end
  end,
  CONFIG.colors.background_mode,
  CONFIG.generation, -- Pass generation config (force_regenerate, colorfulness_threshold)
  color_sources -- Pass color sources config for consistent application after generation
)

-- Track if force_regenerate is active to ensure colors are reloaded on every dashboard render
-- This prevents stale cached colors from being re-applied after async regeneration completes
force_regenerate_active = CONFIG.generation.force_regenerate

if pokemon_colors then
  -- Apply colors to Snacks dashboard highlight groups
  -- Pass background_mode configuration, color source overrides, and adjustments
  visual_utils.apply_dashboard_colors(pokemon_colors, CONFIG.colors.background_mode, color_sources)

  -- Export pokemon colors to env file for tmux/shell integration
  export_pokemon_to_env(pokemon_name, pokemon_shiny, pokemon_form, pokemon_colors, CONFIG.colors.background_mode)
end

-- Check if we should show recent project toggle based on context
-- Now accepts optional force_hide parameter to override normal logic
---@param force_hide? boolean Optional flag to force disable recent files
---@return boolean enabled Whether recent files should be shown
local function recent_project_toggle(force_hide)
  -- If force_hide is true, always return false
  if force_hide then
    return false
  end

  local in_git = Snacks.git.get_root() ~= nil
  local has_two_panes = utils.show_if_has_second_pane()
  -- if in git and has one pane, then we disable
  return not (in_git and not has_two_panes)
end

---Validate and normalize position string
---@param position string|nil Position string to validate
---@return string normalized Valid position string
local function validate_position(position)
  local valid_positions = {
    "top-left",
    "top-middle",
    "top-right",
    "middle-left",
    "middle-middle",
    "middle-right",
    "bottom-left",
    "bottom-middle",
    "bottom-right",
  }

  -- Default position
  if not position or position == "" then
    return "middle-middle"
  end

  -- Check if valid
  if vim.tbl_contains(valid_positions, position) then
    return position
  end

  -- Invalid, use default and warn
  vim.notify(string.format("Invalid pokemon position '%s', using 'middle-middle'", position), vim.log.levels.WARN)
  return "middle-middle"
end

-- Note: is_section_enabled has been moved to utils.lua for reuse
-- Use utils.is_section_enabled throughout this file

---Calculate heights for both panes in a single pass through sections
---@param sections table Array of all section configurations
---@return number pane1_height Total height of pane 1
---@return number pane2_height Total height of pane 2
local function calculate_pane_heights(sections)
  local heights = { [1] = 0, [2] = 0 }

  for _, section in ipairs(sections) do
    if utils.is_section_enabled(section) and section.pane then
      local pane = section.pane

      -- Add main content height
      if section.section == "terminal" then
        heights[pane] = heights[pane] + (section.height or 1)
      elseif section.title or section.desc or section.key then
        heights[pane] = heights[pane] + 1
      end

      -- Add padding
      if section.padding then
        heights[pane] = heights[pane] + section.padding
      end
    end
  end

  return heights[1], heights[2]
end

-- Create search keys section for project operations
-- Returns sections and total height
---@return table sections Array of section configs
---@return number height Total height of this section
local function search_keys()
  local cwd = vim.fn.getcwd()
  local project = vim.fn.fnamemodify(cwd, ":t")
  local header = { pane = 1, title = utils.create_aligned_title("Project", project) }

  local keys = {
    { key = "/", desc = "Grep Text", action = ":lua Snacks.dashboard.pick('live_grep')" },
    {
      desc = "Search Code TODOs",
      key = "x",
      action = function()
        Snacks.picker.todo_comments({ keywords = { "TODO", "FIX", "FIXME", "HACK", "BUG" } })
      end,
    },
    {
      desc = "Grep Dependencies",
      key = "s",
      action = function()
        require("dependency-picker").manual_search("grep")
      end,
    },
    {
      desc = "Open TODO List",
      key = "t",
      action = function()
        todos.open_todo()
      end,
    },
  }

  return utils.create_pane(header, keys, 2)
end

-- Create global keys section for neovim operations
-- Returns sections and total height
---@return table sections Array of section configs
---@return number height Total height of this section
local function globalkeys()
  -- NOTE: consider the projects section that only shows up if not in a git repo
  local header = {
    pane = 1,
    title = utils.create_aligned_title(
      "Neovim",
      "v" .. vim.version().major .. "." .. vim.version().minor .. "." .. vim.version().patch
    ),
  }
  local keys = {
    { key = "q", desc = "Quit", action = ":qa" },
    {
      key = "l",
      desc = "Manage Lua Plugins",
      action = ":Lazy",
      enabled = package.loaded.lazy ~= nil,
    },
    { key = "r", desc = "Restore Session", section = "session" },
  }

  local ok, _ = pcall(require, "obsidian")
  if ok then
    table.insert(keys, 2, {
      key = "n",
      desc = "Open Daily Note",
      action = function()
        vim.cmd("ObsidianToday")
      end,
    })
  else
    table.insert(keys, 2, {
      key = "p",
      desc = "Find Project",
      action = function()
        return Snacks.picker.projects({
          confirm = function(picker, item)
            picker:close()
            vim.api.nvim_set_current_dir(item.file)
            Snacks.dashboard.update()
          end,
        })
      end,
    })
  end

  return utils.create_pane(header, keys, 2)
end

-- Get recent files for the dashboard
-- Returns sections and total height
-- Now accepts optional force_hide parameter to override normal logic
---@param force_hide? boolean Optional flag to force disable recent files
---@return table sections Array of section configs
---@return number height Total height of this section
local function get_recent_files(force_hide)
  local out = {}
  local max_files = 4
  local recent_files = utils.recent_files_in_cwd(max_files)
  local n_files = #recent_files
  local pane = Snacks.git.get_root() and 2 or 1

  -- Create a function that includes force_hide in its closure
  local function enabled_check()
    return recent_project_toggle(force_hide)
  end

  for i, rel in ipairs(recent_files) do
    out[#out + 1] = {
      pane = pane,
      indent = 0,
      padding = 0,
      desc = utils.normalize_path(rel),
      key = tostring(i),
      action = function()
        vim.cmd("edit " .. rel)
      end,
      enabled = enabled_check,
    }
  end
  local final_padding = max_files - n_files + 1

  -- Calculate height: files + final_padding
  -- Note: The "Recent Files" title is added separately in create_sections()
  -- Height is just the number of actual file entries + padding
  -- When n_files = 0, no entry sections are created, so height is just final_padding
  local entries_height = n_files
  local height = entries_height + final_padding

  out[#out + 1] = {
    pane = pane,
    indent = 0,
    padding = final_padding,
    enabled = enabled_check,
  }
  if pane == 2 then
    out[#out + 1] = {
      pane = 2,
      padding = 0,
      indent = 0,
      title = utils.create_separator(),
      enabled = enabled_check,
    }
    height = height + 1
  end

  -- If force_hide is true, return 0 height to reflect that sections are hidden
  if force_hide then
    height = 0
  end

  return out, height
end

---Calculate horizontal positioning for sprite
---@param sprite_width number Width of sprite in characters
---@param pane_width number Total available width in pane
---@param position string Position string (e.g., "top-middle", "middle-left")
---@return number indent Spaces to indent from left edge
local function calculate_horizontal_position(sprite_width, pane_width, position)
  -- Extract horizontal component from position string
  local horizontal = position:match("-(.+)$")

  -- Validate position
  if not horizontal or not vim.tbl_contains({ "left", "middle", "right" }, horizontal) then
    vim.notify(string.format("Invalid position '%s', using middle", position), vim.log.levels.WARN)
    horizontal = "middle"
  end

  local indent = 0
  local margin = 0

  if horizontal == "left" then
    -- Small indent from left edge for margin
    indent = margin
  elseif horizontal == "middle" then
    -- Center horizontally
    -- Use ceil to bias rightward when available_space is odd (more space on left)
    local available_space = pane_width - sprite_width
    indent = math.floor(available_space / 2)
  elseif horizontal == "right" then
    -- Align to right edge with small margin
    local available_space = pane_width - sprite_width
    indent = available_space - margin -- -2 for small margin
  end

  -- Ensure indent is non-negative
  indent = math.max(0, indent)

  -- Handle overflow: if sprite is wider than pane, just left-align
  if sprite_width > pane_width then
    indent = 0
  end

  return indent
end

---Calculate vertical positioning for sprite within fixed-height section
---@param sprite_height number Height of sprite in lines
---@param section_height number Total height of pokemon section (fixed, matches pane 1)
---@param position string Position string (e.g., "top-middle", "middle-left")
---@return number padding_top Lines of padding before sprite
---@return number padding_bottom Lines of padding after sprite
local function calculate_vertical_position(sprite_height, section_height, position)
  -- Extract vertical component from position string
  local vertical = position:match("^([^-]+)")

  -- Validate position
  if not vertical or not vim.tbl_contains({ "top", "middle", "bottom" }, vertical) then
    vim.notify(string.format("Invalid position '%s', using middle", position), vim.log.levels.WARN)
    vertical = "middle"
  end

  -- Calculate available space around sprite
  local available_space = section_height - sprite_height

  -- Handle overflow: if sprite is taller than section, allocate all to sprite
  if available_space < 0 then
    return 0, 0
  end

  local padding_top = 0
  local padding_bottom = 0

  if vertical == "top" then
    -- No padding at top, all padding at bottom
    padding_top = 0
    padding_bottom = available_space
  elseif vertical == "middle" then
    -- Center vertically, split padding evenly
    -- Add 1 extra to padding_top to compensate for the startup line below sprite
    -- This ensures visual symmetry: distance to sprite center from top = distance from sprite center to bottom
    padding_top = math.floor(available_space / 2) + 1
    padding_bottom = available_space - padding_top
  elseif vertical == "bottom" then
    -- All padding at top, no padding at bottom
    padding_top = available_space
    padding_bottom = 0
  end

  return padding_top, padding_bottom
end

-- Create git sections for git operations
-- Returns sections and total height (returns 0 height if not in git repo)
---@param base_branch string Base branch name
---@param current_branch string Current branch name
---@return table sections Array of git section configs
---@return number height Total height of git sections (0 if not in git)
-- Create git sections with optional force_hide parameter
-- When force_hide is true, sections are created but disabled for height calculation
---@param base_branch string Base branch name (usually main or master)
---@param current_branch string Current branch name
---@param force_hide? boolean Optional flag to force disable git sections
---@return table sections Array of git section configs
---@return number height Total height of git sections
local function create_git_sections(base_branch, current_branch, force_hide)
  local in_git = Snacks.git.get_root() ~= nil

  -- If not in git repo or forced to hide, return empty sections with 0 height
  if not in_git or force_hide then
    return {}, 0
  end

  local sections = {
    {
      pane = 1,
      title = utils.create_aligned_title("Git", current_branch),
      indent = 0,
      padding = 2,
      enabled = in_git,
    },
    {
      pane = 1,
      desc = "Checkout Another Branch",
      key = "b",
      action = function()
        Snacks.picker.git_branches({
          all = true,
          confirm = function(picker, item)
            picker:close()
            git_utils.checkout_branch(item.branch)
            Snacks.dashboard.update()
          end,
        })
      end,
      enabled = in_git,
      indent = 0,
    },
    {
      pane = 1,
      desc = string.format("Open Diff vs %s", base_branch),
      key = "d",
      indent = 0,
      action = function()
        local diff = require("custom.git.diff")
        diff.fetch_and_diff(base_branch)
      end,
      enabled = in_git,
    },
    {
      pane = 1,
      indent = 0,
      desc = "Search Un-Commited Changes",
      key = "u",
      action = function()
        Snacks.picker.git_status()
      end,
      enabled = in_git,
    },
    {
      pane = 1,
      desc = "Open LazyGit UI",
      key = "g",
      indent = 0,
      action = function()
        Snacks.lazygit({ cwd = LazyVim.root.git() })
      end,
      padding = 1,
      enabled = in_git,
    },
    {
      pane = 1,
      indent = 0,
      -- Dynamic separator line that scales with pane width
      title = utils.create_separator(),
      padding = 1,
      enabled = in_git,
    },
    {
      pane = 1,
      desc = "Search Recent Notifications",
      key = "N",
      indent = 0,
      action = function()
        vim.notify("Fetching Notifications from GitHub...")
        vim.defer_fn(notifications.picker, 100)
      end,
      enabled = in_git,
    },
    {
      pane = 1,
      desc = "Search Pull Requests",
      indent = 0,
      key = "P",
      action = function()
        Snacks.picker.gh_pr()
      end,
      enabled = in_git,
    },
    {
      pane = 1,
      desc = "Search Issues",
      key = "I",
      indent = 0,
      action = function()
        Snacks.picker.gh_issue()
      end,
      enabled = in_git,
    },
    {
      pane = 1,
      desc = "Open Repo in GitHub",
      padding = 2,
      key = "B",
      indent = 0,
      action = function()
        Snacks.gitbrowse()
      end,
      enabled = in_git,
    },
  }

  -- Calculate height dynamically from sections
  -- This replaces the hardcoded calculation and ensures accuracy
  local height = utils.calculate_section_group_height(sections)

  return sections, height
end

---Create pokemon section with fixed height matching other pane
---@param target_height number Total height this section must occupy
---@param hide_git? boolean Whether git sections are hidden
---@param hide_recent? boolean Whether recent files sections are hidden
---@return table sections Pokemon section configuration
local function create_pokemon_section(target_height, hide_git, hide_recent)
  -- Validate position configuration
  local position = validate_position(CONFIG.pokemon.position)

  -- Detect sprite dimensions using two-pass auto-sizing
  local sprite_width, sprite_height, use_big =
    visual_utils.detect_sprite_dimensions_auto(pokemon_name, pokemon_shiny, pokemon_form, CONFIG.pokemon.force_small)

  if not sprite_width or not sprite_height then
    -- Dimension detection failed, return empty section with target height
    vim.notify("Failed to detect pokemon sprite dimensions, using empty section", vim.log.levels.WARN)
    return {
      {
        pane = 2,
        padding = target_height,
        enabled = utils.show_if_has_second_pane,
      },
    }
  end

  -- Calculate horizontal position (indent)
  -- Uses Snacks.config.dashboard.width which is set dynamically by create_sections()
  local indent = calculate_horizontal_position(sprite_width, Snacks.config.dashboard.width, position)

  -- Calculate vertical position within fixed-height section
  -- Note: We need to account for the startup time line and extra padding sources that somehow are not identified
  -- which ends up being different if there is one or two panes.

  local pokemon_section_height = target_height

  local in_git = Snacks.git.get_root() ~= nil
  local both_hidden = hide_git and hide_recent

  -- Adjust height based on what sections are shown:
  -- - If both git and recent are hidden: -3
  -- - If has two panes and in git: -4
  -- - Otherwise: -2
  if both_hidden then
    pokemon_section_height = target_height - 3
  elseif utils.show_if_has_second_pane() and in_git then
    pokemon_section_height = target_height - 4
  else
    pokemon_section_height = target_height - 2
  end
  -- local pokemon_section_height = target_height - 4
  local padding_top, padding_bottom = calculate_vertical_position(sprite_height, pokemon_section_height, position)

  -- Build pokemon command with correct -b flag
  local pokemon_cmd = visual_utils.build_pokemon_command(pokemon_name, pokemon_shiny, pokemon_form, use_big)

  return {
    -- Top padding section (if any)
    {
      pane = 2,
      padding = padding_top,
      enabled = utils.show_if_has_second_pane,
    },
    -- Pokemon sprite terminal section
    {
      pane = 2,
      section = "terminal",
      cmd = pokemon_cmd,
      ttl = math.huge, -- Cache forever so the 1 second pause is only the first time
      indent = indent,
      height = pokemon_section_height - padding_top - padding_bottom,
      enabled = utils.show_if_has_second_pane,
    },
    -- Bottom padding section (if any)
    {
      pane = 2,
      padding = padding_bottom,
      enabled = utils.show_if_has_second_pane,
    },
    -- Startup time (appears after pokemon)
    {
      pane = 2,
      title = utils.create_aligned_title("Startup", vim.fn.printf("%.1fms", require("lazy").stats().startuptime)),
      indent = 0,
      enabled = utils.show_if_has_second_pane,
    },
  }
end

-- Helper function to create all non-pokemon sections
-- Extracted to allow two-pass creation for proper width calculation
-- Now accepts optional hiding flags to control git and recent files visibility
---@param in_git boolean Whether we're in a git repository
---@param base_branch string Base branch name (usually main or master)
---@param current_branch string Current branch name
---@param hide_git? boolean Optional flag to force hide git sections
---@param hide_recent? boolean Optional flag to force hide recent files sections
local function create_all_sections_without_pokemon(in_git, base_branch, current_branch, hide_git, hide_recent)
  -- Build all section groups (must be inside helper to use correct width)
  -- Pass hiding flags to the relevant section creators
  local search_sections, _ = search_keys()
  local files_sections, _ = get_recent_files(hide_recent)
  local git_sections, _ = create_git_sections(base_branch, current_branch, hide_git)
  local global_sections, _ = globalkeys()

  local sections = {}

  -- Add separator to pane 2 for visual balance in these cases:
  -- 1. When BOTH git and recent are hidden (always show for visual balance)
  -- 2. When recent files are in pane 1 (not in git) and shown
  -- 3. When recent files would be in pane 2 (in git) but are hidden
  local both_hidden = hide_git and hide_recent
  local show_pane2_separator = utils.show_if_has_second_pane()
    and (
      both_hidden -- Case 1: Both hidden, always need separator
      or (not in_git and recent_project_toggle(hide_recent)) -- Case 2: Recent in left pane and shown
      or (in_git and not recent_project_toggle(hide_recent)) -- Case 3: Recent would be in right pane but hidden
    )

  if show_pane2_separator then
    table.insert(sections, {
      pane = 2,
      title = utils.create_separator(),
      indent = 0,
      padding = 0,
    })
  end

  -- Search keys section
  vim.list_extend(sections, search_sections)

  -- Recent files title
  -- Create enabled function that checks hide_recent flag
  local function recent_title_enabled()
    return recent_project_toggle(hide_recent)
  end

  table.insert(sections, {
    title = utils.create_aligned_title("Recent Files", utils.get_recent_file_time()),
    pane = in_git and 2 or 1,
    indent = 0,
    padding = 2,
    enabled = recent_title_enabled,
  })

  -- Recent files entries
  vim.list_extend(sections, files_sections)

  -- Git sections (automatically disabled if not in git via enabled field)
  vim.list_extend(sections, git_sections)

  -- Global keys section
  vim.list_extend(sections, global_sections)

  -- Time section
  table.insert(sections, {
    pane = 1,
    title = utils.create_aligned_title("Time", os.date("%H:%M")),
    indent = 0,
  })

  return sections
end

-- Create all dashboard sections
-- Called by Snacks dashboard with self (dashboard instance) as parameter
---@param dashboard snacks.dashboard.Class Dashboard instance
function M.create_sections(dashboard)
  -- Ensure tabline is always shown to prevent layout shifts (only in tmux)
  -- This prevents the dashboard from jumping when switching buffers in tmux
  -- Outside tmux, we don't need this workaround as there's no tmux status bar
  if vim.env.TMUX then
    local original_tabline = vim.o.tabline
    vim.o.tabline = " "
    vim.o.showtabline = 2

    -- Restore tabline when leaving dashboard
    vim.api.nvim_create_autocmd("BufLeave", {
      pattern = "*",
      once = true,
      callback = function()
        if vim.bo.filetype == "snacks_dashboard" then
          vim.o.tabline = original_tabline
        end
      end,
    })
  end
  -- Always set initial dynamic pane width for responsive layout
  -- This will be recalculated after height calculation for perfect centering
  if dashboard and dashboard._size then
    local dynamic_width = utils.calculate_dynamic_pane_width(dashboard._size.width)
    -- Set both for Snacks internal layout AND our utility functions
    dashboard.opts.width = dynamic_width
    dashboard.opts.pane_gap = 4 -- Initialize pane gap with default (will be recalculated later if dynamic)
    Snacks.config.dashboard.width = dynamic_width
    -- Initialize with default values (will be recalculated later)
    Snacks.config.dashboard.edge_margin = 4
    Snacks.config.dashboard.pane_gap = 4
  end

  -- Re-check for pokemon colors (in case async generation completed)
  -- Always reload when force_regenerate is active to pick up newly regenerated colors
  if (not pokemon_colors or force_regenerate_active) and pokemon_name then
    -- Reload the pokemon-colors module to pick up any newly generated colors
    -- This is important when force_regenerate=true and colors are being regenerated
    package.loaded["custom.visual.pokemon-colors"] = nil
    pokemon_colors = visual_utils.get_pokemon_colors(pokemon_name, pokemon_shiny, pokemon_form, false)
  end

  -- Re-apply pokemon colors when dashboard opens
  -- This ensures colors are correct even after colorscheme reloads or async generation
  if pokemon_colors then
    visual_utils.apply_dashboard_colors(pokemon_colors, CONFIG.colors.background_mode, color_sources)
  end

  -- Get base branch for git sections
  local base_branch = git_utils.get_base_branch()
  local current_branch = git_utils.get_current_branch()
  local in_git = Snacks.git.get_root() ~= nil

  -- FIRST PASS: Create sections to calculate height
  -- This pass is only for height calculation, sections will be recreated
  local temp_sections = create_all_sections_without_pokemon(in_git, base_branch, current_branch)

  -- ✨ Calculate both pane heights from first pass
  local pane1_height, pane2_height = calculate_pane_heights(temp_sections)

  -- Check if we need to hide sections due to height constraints
  local hide_git, hide_recent = false, false
  if dashboard and dashboard._size then
    local terminal_height = dashboard._size.height

    -- If pane 1 height exceeds terminal height, we need to hide sections
    if pane1_height > terminal_height then
      -- Calculate the height of git and recent files sections from temp_sections
      local git_height = utils.calculate_git_sections_height(temp_sections)
      local recent_height = utils.calculate_recent_files_height(temp_sections)

      -- Simple strategy: hide both if their combined height would make it fit
      local reduced_height = pane1_height - git_height - recent_height
      if reduced_height <= terminal_height then
        hide_git = true
        hide_recent = true

        -- Recalculate heights with hiding flags to get accurate new heights
        temp_sections = create_all_sections_without_pokemon(in_git, base_branch, current_branch, hide_git, hide_recent)
        pane1_height, pane2_height = calculate_pane_heights(temp_sections)
      else
        -- Even with both hidden, still too tall - hide them anyway for best effort
        hide_git = true
        hide_recent = true

        vim.notify("Dashboard content still exceeds terminal height even with sections hidden", vim.log.levels.WARN)

        -- Recalculate heights with hiding flags
        temp_sections = create_all_sections_without_pokemon(in_git, base_branch, current_branch, hide_git, hide_recent)
        pane1_height, pane2_height = calculate_pane_heights(temp_sections)
      end
    end
  end

  -- 🎨 Recalculate width with exact vertical margin for perfect centering
  -- Account for terminal character aspect ratio (chars are taller than wide)
  if dashboard and dashboard._size then
    -- Calculate vertical margin in rows (using dashboard height for accuracy)
    local vertical_margin_rows = math.max(math.floor((dashboard._size.height - pane1_height) / 2), 0)

    -- on my setup this looks right --- unclear how to make this dynamic
    local aspect_ratio = 2.5 -- Adjust this if your font looks different

    -- Convert vertical rows to equivalent horizontal columns
    local equivalent_horizontal_margin = math.floor(vertical_margin_rows * aspect_ratio)

    -- Use max(4, ...) as minimum padding for aesthetics
    local edge_margin = math.max(4, equivalent_horizontal_margin)
    local optimized_width = utils.calculate_dynamic_pane_width(dashboard._size.width, edge_margin)
    -- Update both for Snacks internal layout AND our utility functions
    dashboard.opts.width = optimized_width
    -- Set pane gap based on feature flag
    local pane_gap
    if CONFIG.dynamic_pane_gap then
      pane_gap = edge_margin -- Use dynamic gap matching edge margins
    else
      pane_gap = 4 -- Use Snacks default gap
    end
    dashboard.opts.pane_gap = pane_gap -- Tell Snacks what gap to use
    Snacks.config.dashboard.width = optimized_width
    -- Store both edge_margin and actual pane_gap for use in other functions
    Snacks.config.dashboard.edge_margin = edge_margin -- Always store edge_margin
    Snacks.config.dashboard.pane_gap = pane_gap -- Store actual gap being used
  end

  -- SECOND PASS: Recreate sections with the correct width for proper title alignment
  -- This two-pass approach ensures that titles are aligned with the final calculated width
  -- Now also applies the hiding flags determined in Pass 1
  -- Performance impact is negligible (microseconds) as we're just creating Lua tables
  local final_sections = create_all_sections_without_pokemon(in_git, base_branch, current_branch, hide_git, hide_recent)

  -- Create pokemon section to fill the gap between pane2 and pane1
  -- This ensures both panes have identical total heights
  -- Pass hiding flags to adjust height calculation properly
  local pokemon_sections = create_pokemon_section(pane1_height - pane2_height, hide_git, hide_recent)
  vim.list_extend(final_sections, pokemon_sections)

  return final_sections
end

return M
