return {
  --   "Vigemus/iron.nvim",
  --   config = function()
  --     local iron = require("iron.core")
  --     local common = require("iron.fts.common")
  --
  --     iron.setup({
  --       config = {
  --         -- Whether a repl should be discarded or not
  --         scratch_repl = true,
  --         -- Your repl definitions come here
  --         repl_definition = {
  --           sh = {
  --             -- Can be a table or a function that
  --             -- returns a table (see below)
  --             command = { "zsh" },
  --           },
  --           python = {
  --             command = { "ipython", "--no-autoindent" },
  --             format = common.bracketed_paste_python,
  --             block_dividers = { "# %%", "#%%" },
  --           },
  --         },
  --         repl_filetype = function(bufnr, ft)
  --           return ft
  --           -- or return a string name such as the following
  --           -- return "iron"
  --         end,
  --         -- How the repl window will be displayed
  --         -- See below for more information
  --         repl_open_cmd = require("iron.view").top("20%"),
  --       },
  --       -- Iron doesn't set keymaps by default anymore.
  --       -- You can set them here or manually add keymaps to the functions in iron.core
  --       keymaps = {
  --         toggle_repl = "<leader>py",
  --         send_motion = "<leader>psc",
  --         visual_send = "<leader>psc",
  --         send_file = "<leader>psf",
  --         send_line = "<leader>psl",
  --         send_mark = "<leader>psm",
  --         mark_motion = "<leader>pmc",
  --         mark_visual = "<space>mc",
  --         remove_mark = "<space>md",
  --         cr = "<space>s<cr>",
  --         interrupt = "<leader>pi",
  --         exit = "<leader>pq",
  --         clear = "<leader>pc",
  --       },
  --       -- If the highlight is on, you can change how it looks
  --       -- For the available options, check nvim_set_hl
  --       highlight = {
  --         italic = true,
  --       },
  --       ignore_blank_lines = true, -- ignore blank lines when sending visual select lines
  --     })
  --
  --     -- iron also has a list of commands, see :h iron-commands for all available commands
  --     -- vim.keymap.set("n", "<space>rs", "<cmd>IronRepl<cr>")
  --     -- vim.keymap.set("n", "<space>rr", "<cmd>IronRestart<cr>")
  --     -- vim.keymap.set("n", "<space>rf", "<cmd>IronFocus<cr>")
  --     -- vim.keymap.set("n", "<space>rh", "<cmd>IronHide<cr>")
  --   end,
}
