-- NOTE: this requires openjdk@17 to be installed
return {
  url = "https://gitlab.com/schrieveslaach/sonarlint.nvim",
  ft = { "python" },
  config = function()
    require("sonarlint").setup({
      server = {
        cmd = {
          "sonarlint-language-server",
          "-stdio",
          "-analyzers",
          vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarpython.jar"),
        },
        -- TODO: figure out how to let this change per project and inherit real sonarqube profiles
        settings = {
          sonarlint = {
            rules = {
              -- python rules from workspace. generated from script. TODO: integrate with actual sonarqube server
              ["python:BackticksUsage"] = { level = "on" },
              ["python:ExecStatementUsage"] = { level = "on" },
              ["python:InequalityUsage"] = { level = "on" },
              ["python:LineLength"] = { level = "on", parameters = { maximumLineLength = 120 } },
              ["python:OneStatementPerLine"] = { level = "on" },
              ["python:ParsingError"] = { level = "on" },
              ["python:PreIncrementDecrement"] = { level = "on" },
              ["python:PrintStatementUsage"] = { level = "on" },
              ["python:S100"] = { level = "on", parameters = { format = "^[a-z_][a-z0-9_]*$" } },
              ["python:S101"] = { level = "on", parameters = { format = "^_?([A-Z_][a-zA-Z0-9]*|[a-z_][a-z0-9_]*)$" } },
              ["python:S104"] = { level = "on", parameters = { maximum = 1000 } },
              ["python:S1045"] = { level = "on" },
              ["python:S1066"] = { level = "on" },
              ["python:S107"] = { level = "on", parameters = { max = 15 } },
              ["python:S108"] = { level = "on" },
              ["python:S1110"] = { level = "on" },
              ["python:S112"] = { level = "on" },
              ["python:S113"] = { level = "on" },
              ["python:S1131"] = { level = "on" },
              ["python:S1142"] = { level = "on", parameters = { max = 15 } },
              ["python:S1143"] = { level = "on" },
              ["python:S1144"] = { level = "on" },
              ["python:S116"] = { level = "on", parameters = { format = "^[_a-z][_a-z0-9]*$" } },
              ["python:S117"] = { level = "on", parameters = { format = "^[_a-z][a-z0-9_]*$" } },
              ["python:S1186"] = { level = "on" },
              ["python:S1192"] = { level = "on", parameters = { threshold = 10 } },
              ["python:S1226"] = { level = "on" },
              ["python:S125"] = { level = "on", parameters = { exception = "(fmt|pyw+):.*" } },
              ["python:S1313"] = { level = "on" },
              ["python:S134"] = { level = "on", parameters = { max = 4 } },
              ["python:S138"] = { level = "on", parameters = { max = 150 } },
              ["python:S1481"] = { level = "on", parameters = { regex = "(_[a-zA-Z0-9_]*|dummy|unused|ignored)" } },
              ["python:S1515"] = { level = "on" },
              ["python:S1542"] = { level = "on", parameters = { format = "^[a-z_][a-z0-9_]*$" } },
              ["python:S1578"] = { level = "on", parameters = { format = "(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$" } },
              ["python:S1656"] = { level = "on" },
              ["python:S1700"] = { level = "on" },
              ["python:S1716"] = { level = "on" },
              ["python:S1751"] = { level = "on" },
              ["python:S1763"] = { level = "on" },
              ["python:S1764"] = { level = "on" },
              ["python:S1845"] = { level = "on" },
              ["python:S1854"] = { level = "on" },
              ["python:S1862"] = { level = "on" },
              ["python:S1871"] = { level = "on" },
              ["python:S2053"] = { level = "on" },
              ["python:S2068"] = { level = "on", parameters = { credentialWords = "password,passwd,pwd,passphrase" } },
              ["python:S2077"] = { level = "on" },
              ["python:S2092"] = { level = "on" },
              ["python:S2115"] = { level = "on" },
              ["python:S2159"] = { level = "on" },
              ["python:S2190"] = { level = "on" },
              ["python:S2201"] = { level = "on" },
              ["python:S2208"] = { level = "on" },
              ["python:S2257"] = { level = "on" },
              ["python:S2275"] = { level = "on" },
              ["python:S2612"] = { level = "on" },
              ["python:S2638"] = { level = "on" },
              ["python:S2710"] = { level = "on", parameters = { classParameterNames = "cls,mcs,metacls" } },
              ["python:S2711"] = { level = "on" },
              ["python:S2712"] = { level = "on" },
              ["python:S2734"] = { level = "on" },
              ["python:S2737"] = { level = "on" },
              ["python:S2755"] = { level = "on" },
              ["python:S2757"] = { level = "on" },
              ["python:S2772"] = { level = "on" },
              ["python:S2823"] = { level = "on" },
              ["python:S2836"] = { level = "on" },
              ["python:S3329"] = { level = "on" },
              ["python:S3330"] = { level = "on" },
              ["python:S3358"] = { level = "on" },
              ["python:S3403"] = { level = "on" },
              ["python:S3457"] = { level = "on" },
              ["python:S3516"] = { level = "on" },
              ["python:S3626"] = { level = "on" },
              ["python:S3752"] = { level = "on" },
              ["python:S3776"] = { level = "on", parameters = { threshold = 35 } },
              ["python:S3827"] = { level = "on" },
              ["python:S3862"] = { level = "on" },
              ["python:S3923"] = { level = "on" },
              ["python:S3981"] = { level = "on" },
              ["python:S3984"] = { level = "on" },
              ["python:S3985"] = { level = "on" },
              ["python:S4143"] = { level = "on" },
              ["python:S4144"] = { level = "on" },
              ["python:S4423"] = { level = "on" },
              ["python:S4426"] = { level = "on" },
              ["python:S4433"] = { level = "on" },
              ["python:S4487"] = { level = "on", parameters = { enableSingleUnderscoreIssues = "false" } },
              ["python:S4502"] = { level = "on" },
              ["python:S4507"] = { level = "on" },
              ["python:S4790"] = { level = "on" },
              ["python:S4828"] = { level = "on" },
              ["python:S4830"] = { level = "on" },
              ["python:S5042"] = { level = "on" },
              ["python:S5122"] = { level = "on" },
              ["python:S5247"] = { level = "on" },
              ["python:S5332"] = { level = "on" },
              ["python:S5443"] = { level = "on" },
              ["python:S5445"] = { level = "on" },
              ["python:S5527"] = { level = "on" },
              ["python:S5542"] = { level = "on" },
              ["python:S5547"] = { level = "on" },
              ["python:S5549"] = { level = "on" },
              ["python:S5603"] = { level = "on" },
              ["python:S5607"] = { level = "on" },
              ["python:S5632"] = { level = "on" },
              ["python:S5644"] = { level = "on" },
              ["python:S5655"] = { level = "on" },
              ["python:S5659"] = { level = "on" },
              ["python:S5685"] = { level = "on" },
              ["python:S5704"] = { level = "on" },
              ["python:S5706"] = { level = "on" },
              ["python:S5707"] = { level = "on" },
              ["python:S5708"] = { level = "on" },
              ["python:S5709"] = { level = "on" },
              ["python:S5712"] = { level = "on" },
              ["python:S5713"] = { level = "on" },
              ["python:S5714"] = { level = "on" },
              ["python:S5717"] = { level = "on" },
              ["python:S5719"] = { level = "on" },
              ["python:S5720"] = { level = "on", parameters = { ignoredDecorators = "abstractmethod" } },
              ["python:S5722"] = { level = "on" },
              ["python:S5724"] = { level = "on" },
              ["python:S5727"] = { level = "on" },
              ["python:S5747"] = { level = "on" },
              ["python:S5754"] = { level = "on" },
              ["python:S5756"] = { level = "on" },
              ["python:S5780"] = { level = "on" },
              ["python:S5781"] = { level = "on" },
              ["python:S5795"] = { level = "on" },
              ["python:S5796"] = { level = "on" },
              ["python:S5797"] = { level = "on" },
              ["python:S5799"] = { level = "on" },
              ["python:S5806"] = { level = "on" },
              ["python:S5807"] = { level = "on" },
              ["python:S5828"] = { level = "on" },
              ["python:S5843"] = { level = "on", parameters = { maxComplexity = 20 } },
              ["python:S5856"] = { level = "on" },
              ["python:S5864"] = { level = "on" },
              ["python:S5886"] = { level = "on" },
              ["python:S5890"] = { level = "on" },
              ["python:S5899"] = { level = "on" },
              ["python:S5953"] = { level = "on" },
              ["python:S905"] = {
                level = "on",
                parameters = { ignoredOperators = "<<,>>,|", reportOnStrings = "false" },
              },
              ["python:S930"] = { level = "on" },
              ["pythonsecurity:S2076"] = { level = "on" },
              ["pythonsecurity:S2078"] = { level = "on" },
              ["pythonsecurity:S2083"] = { level = "on" },
              ["pythonsecurity:S2091"] = { level = "on" },
              ["pythonsecurity:S2631"] = { level = "on" },
              ["pythonsecurity:S3649"] = { level = "on" },
              ["pythonsecurity:S5131"] = { level = "on" },
              ["pythonsecurity:S5135"] = { level = "on" },
              ["pythonsecurity:S5144"] = { level = "on" },
              ["pythonsecurity:S5145"] = { level = "on" },
              ["pythonsecurity:S5146"] = { level = "on" },
              ["pythonsecurity:S5334"] = { level = "on" },
              ["pythonsecurity:S5496"] = { level = "on" },
              ["pythonsecurity:S6287"] = { level = "on" },
            },
          },
        },
      },
      filetypes = {
        "python",
      },
    })
  end,
}
