# Interactive shell configuration. Keybindings follow README: Conventions.

# Repo root, derived from this file's own symlink — works wherever the repo
# lives, with no hardcoded path. %x is the file currently being sourced.
typeset -g DOTFILES_DIR="${${(%):-%x}:A:h:h}"

# ----- history ---------------------------------------------------------
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS HIST_VERIFY

# ----- completion ------------------------------------------------------
autoload -Uz compinit && compinit
# Case-insensitive matching.
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# ----- functions -------------------------------------------------------
source "$HOME/.config/zsh/functions/vi-mode.zsh"
source "$HOME/.config/zsh/functions/venv.zsh"
vi_mode_init
venv_init

# The prompt owns the venv indicator; activate must not inject its own.
export VIRTUAL_ENV_DISABLE_PROMPT=1

# ----- plugins (cloned by install.sh) ----------------------------------
# Order matters: fzf-tab needs compinit first; syntax highlighting goes last.
ZSH_PLUGINS="$HOME/.local/share/zsh/plugins"

if [[ -r "$ZSH_PLUGINS/fzf-tab/fzf-tab.plugin.zsh" ]]; then
  source "$ZSH_PLUGINS/fzf-tab/fzf-tab.plugin.zsh"
  # Convention: Tab is menu completion. (Bind after vi_mode_init, which resets keymaps.)
  bindkey -M viins '^I' fzf-tab-complete
  # fzf-tab ignores FZF_DEFAULT_OPTS unless told otherwise; without this the
  # popup would stay default-colored while plain fzf follows the theme.
  zstyle ':fzf-tab:*' use-fzf-default-opts yes
fi

if [[ -r "$ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh"
  # Convention: Shift-Tab accepts ghost text.
  bindkey -M viins '^[[Z' autosuggest-accept
fi

if [[ -r "$ZSH_PLUGINS/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh" ]]; then
  source "$ZSH_PLUGINS/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
fi

# ----- theme -----------------------------------------------------------
# Generated by the `theme` command; see README: Theming.
THEME_GENERATED="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles/generated"

if [[ -r "$THEME_GENERATED/shell-colors.zsh" ]]; then
  source "$THEME_GENERATED/shell-colors.zsh"
  # Re-source when `theme` regenerates, so running shells follow a switch.
  zmodload -F zsh/stat b:zstat
  typeset -g _THEME_COLORS_MTIME="$(zstat +mtime "$THEME_GENERATED/shell-colors.zsh" 2> /dev/null)"
  _theme_refresh() {
    local mtime="$(zstat +mtime "$THEME_GENERATED/shell-colors.zsh" 2> /dev/null)"
    if [[ "$mtime" != "$_THEME_COLORS_MTIME" ]]; then
      typeset -g _THEME_COLORS_MTIME="$mtime"
      source "$THEME_GENERATED/shell-colors.zsh"
    fi
  }
  autoload -U add-zsh-hook
  add-zsh-hook precmd _theme_refresh
fi

[[ -f "$THEME_GENERATED/starship.toml" ]] && export STARSHIP_CONFIG="$THEME_GENERATED/starship.toml"

# ----- prompt ----------------------------------------------------------
command -v starship > /dev/null && eval "$(starship init zsh)"
